package dev.matthiesen.common.cobblemon_boosters.config;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;
import dev.matthiesen.common.cobblemon_boosters.CobblemonBoosters;
import dev.matthiesen.common.cobblemon_boosters.managers.BoostManager;
import dev.matthiesen.common.cobblemon_boosters.data.CatchBoost;
import dev.matthiesen.common.cobblemon_boosters.data.ExperienceBoost;
import dev.matthiesen.common.cobblemon_boosters.data.ShinyBoost;
import dev.matthiesen.common.cobblemon_boosters.data.SpawnBucketBoost;

import java.util.ArrayList;
import java.util.List;

public class CacheConfig {
    @SuppressWarnings("unused")
    @SerializedName("_NOTE")
    public String noEdit = "DO NOT EDIT THIS FILE MANUALLY. This file is used for caching active and queued boosts. Editing this file may cause issues with your boosts.";

    @SerializedName("activeShinyBoost")
    public ShinyBoost activeShinyBoost = null;

    @SerializedName("activeCatchBoost")
    public CatchBoost activeCatchBoost = null;

    @SerializedName("activeExperienceBoost")
    public ExperienceBoost activeExperienceBoost = null;

    @SerializedName("activeSpawnBucketBoost")
    public SpawnBucketBoost activeSpawnBucketBoost = null;

    @SerializedName("queuedShinyBoosts")
    public List<ShinyBoost> queuedShinyBoosts = new ArrayList<>();

    @SerializedName("queuedCatchBoosts")
    public List<CatchBoost> queuedCatchBoosts = new ArrayList<>();

    @SerializedName("queuedExperienceBoosts")
    public List<ExperienceBoost> queuedExperienceBoosts = new ArrayList<>();

    @SerializedName("queuedSpawnBucketBoosts")
    public List<SpawnBucketBoost> queuedSpawnBucketBoosts = new ArrayList<>();

    @SuppressWarnings("unused")
    public CacheConfig() {}

    public CacheConfig(
            ShinyBoost activeShinyBoost, CatchBoost activeCatchBoost, ExperienceBoost activeExperienceBoost, SpawnBucketBoost activeSpawnBucketBoost,
            List<ShinyBoost> queuedShinyBoosts, List<CatchBoost> queuedCatchBoosts, List<ExperienceBoost> queuedExperienceBoosts, List<SpawnBucketBoost> queuedSpawnBucketBoosts
    ) {
        this.activeShinyBoost = activeShinyBoost;
        this.activeCatchBoost = activeCatchBoost;
        this.activeExperienceBoost = activeExperienceBoost;
        this.activeSpawnBucketBoost = activeSpawnBucketBoost;
        this.queuedShinyBoosts = queuedShinyBoosts;
        this.queuedCatchBoosts = queuedCatchBoosts;
        this.queuedExperienceBoosts = queuedExperienceBoosts;
        this.queuedSpawnBucketBoosts = queuedSpawnBucketBoosts;
    }

    public static void setGlobalBoostData() {
        BoostManager bm = CobblemonBoosters.INSTANCE.boostManager;
        CobblemonBoosters.INSTANCE.CACHE_CONFIG_MANAGER.setConfig(new CacheConfig(
                bm.getShinyBoostManager().getActive(),
                bm.getCatchBoostManager().getActive(),
                bm.getExperienceBoostManager().getActive(),
                bm.getSpawnBucketBoostManager().getActive(),
                bm.getShinyBoostManager().getQueue().stream().toList(),
                bm.getCatchBoostManager().getQueue().stream().toList(),
                bm.getExperienceBoostManager().getQueue().stream().toList(),
                bm.getSpawnBucketBoostManager().getQueue().stream().toList()
        ));
    }

    @SuppressWarnings("unused")
    public static final Gson GSON = new GsonBuilder()
            .disableHtmlEscaping()
            .setPrettyPrinting()
            .create();
}
