package dev.matthiesen.cobblemon_boosters.common.config;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.annotations.SerializedName;
import dev.matthiesen.cobblemon_boosters.common.CobblemonBoosters;
import dev.matthiesen.cobblemon_boosters.common.managers.BoostManager;
import dev.matthiesen.cobblemon_boosters.common.data.CatchBoost;
import dev.matthiesen.cobblemon_boosters.common.data.ExperienceBoost;
import dev.matthiesen.cobblemon_boosters.common.data.ShinyBoost;
import dev.matthiesen.cobblemon_boosters.common.data.SpawnBucketBoost;

import java.util.ArrayList;
import java.util.List;

public final class CacheConfig {
    @SuppressWarnings("unused")
    @SerializedName("_NOTE")
    public String noEdit = "DO NOT EDIT THIS FILE MANUALLY. This file is used for caching active and queued boosts. Editing this file may cause issues with your boosts.";

    @SerializedName("activeShinyBoost")
    public ShinyBoost activeShinyBoost = null;

    @SerializedName("activeCatchBoost")
    public CatchBoost activeCatchBoost = null;

    @SerializedName("activeExperienceBoost")
    public ExperienceBoost activeExperienceBoost = null;

    @SerializedName("activeSpawnBucketBoost")
    public SpawnBucketBoost activeSpawnBucketBoost = null;

    @SerializedName("queuedShinyBoosts")
    public List<ShinyBoost> queuedShinyBoosts = new ArrayList<>();

    @SerializedName("queuedCatchBoosts")
    public List<CatchBoost> queuedCatchBoosts = new ArrayList<>();

    @SerializedName("queuedExperienceBoosts")
    public List<ExperienceBoost> queuedExperienceBoosts = new ArrayList<>();

    @SerializedName("queuedSpawnBucketBoosts")
    public List<SpawnBucketBoost> queuedSpawnBucketBoosts = new ArrayList<>();

    @SuppressWarnings("unused")
    public CacheConfig() {}

    public CacheConfig(
            BoostManager.IBoostManager<ShinyBoost> shinyBoostManager,
            BoostManager.IBoostManager<CatchBoost> catchBoostManager,
            BoostManager.IBoostManager<ExperienceBoost> experienceBoostManager,
            BoostManager.IBoostManager<SpawnBucketBoost> spawnBucketBoostManager
    ) {
        this.activeShinyBoost = shinyBoostManager.getActive();
        this.activeCatchBoost = catchBoostManager.getActive();
        this.activeExperienceBoost = experienceBoostManager.getActive();
        this.activeSpawnBucketBoost = spawnBucketBoostManager.getActive();
        this.queuedShinyBoosts = shinyBoostManager.getQueueList();
        this.queuedCatchBoosts = catchBoostManager.getQueueList();
        this.queuedExperienceBoosts = experienceBoostManager.getQueueList();
        this.queuedSpawnBucketBoosts = spawnBucketBoostManager.getQueueList();
    }

    public static void setGlobalBoostData() {
        var shinyBoostManager = BoostManager.getShinyBoostManager();
        var catchBoostManager = BoostManager.getCatchBoostManager();
        var experienceBoostManager = BoostManager.getExperienceBoostManager();
        var spawnBucketBoostManager = BoostManager.getSpawnBucketBoostManager();

        CobblemonBoosters.INSTANCE.getCacheConfigManager().setConfig(new CacheConfig(
                shinyBoostManager,
                catchBoostManager,
                experienceBoostManager,
                spawnBucketBoostManager
        ));
    }

    @SuppressWarnings("unused")
    public static final Gson GSON = new GsonBuilder()
            .disableHtmlEscaping()
            .setPrettyPrinting()
            .create();
}
